---
title: "RIEFOLI"
author: "Javier Gonzalez Canales"
format: html
editor: visual
---

## RIEFOLI

El IMIDRA está llevando a cabo el proyecto RIEFOLI en un olivar intensivo en la finca experimental "La chimenea", (Aranjuez-Colmenar de oreja). En este se proyecto se combina el uso de cuatro tramientos de cubiertas vegetales: (Cubierta de graminea (Brachipodium), Cubierta de leguminosas (Yeros), Cubierta vegetal espontánea y laboreo), con cuatro dosis de riego, (Riego completo (cubriendo las necesidades hidricas del árbol), Riego deficitario controlado, (Redución al 70% la dosis de riego completo, en un momento fenologico determinado), Riego soporte (Un aporte de 1500m3/año distribuidos a lo largo de la campaña de verano) y secano. En este proyecto se estudian los cambios en las propiedades fisico-quimicas (Materia orgánica, Calcimetría, analisis de macro y micro elementos del suelo, contenido de agua del suelo textura, porosidad, infiltración, resistencia a la pentetración....) microbiológicas (respiración basal del suelo, actividad enzimática, abundancia de Hongos, bacterias y arqueas). En el arbol se mide estrés hídrico, fotosísntesis, anchura de tronco, floración, maduración del fruto y produción de aceitunas. Tambien se elaborará aceite donde se medirá la producción industrial de aceite, el contenido en polifenoles y el contenido en pigmentos. En este trabajo se quiere relaccionar el contenido en polifenoles con los diferentes tratamientos y la producción de aceitunas.

```{r}
#Cargamos los datos de excel

library(readxl)
library(tidyverse)
library(tidyr)
library(maps)
library(pacman)
pacman::p_load(here, easyclimate, patchwork, viridis, ggmisc, fs, future, furrr, rmarkdown) 
library(remotes)
library(easyclimate)

polif <- read_csv(file = here("DATOS", "polifenoles.csv"))
produ<- read_csv(file = here("DATOS", "produccion.csv"))

names(polif)

```

Hacemos los datos tidy
